### ISSUE TITLE
Should Bash be Python in the box heading?

### ISSUE THREAD

**Issue by anthony-evans** [UoMResearchIT/programming_with_python#1]
<details>
<summary><strong>Box Headings</strong></summary>

Should "Bash" be changed to "Python" ?

\- The Carpentries
![bash-python](https://user-images.githubusercontent.com/57145243/117206412-bf65bb80-adea-11eb-8d25-00482f56931d.JPG)

</details>

**Comment by douglowe** [comment]
definitely should be - I'll correct this too!
